#include "OOOUnitTestDefines.h"
#include "OOOCount.h"
#include "OOOPre.h"
#include "OOOPost.h"
#include "OOOSimplePaste.h"
#include "OOOQuote.h"
#include "OOOForEach.h"

#define TEST_RESULT_2_ARGS	\
	"FUNCTION_DECLARE apple; FUNCTION_DECLARE banana; " \
	"FIELD_DECLARE foo; FIELD_DECLARE bar; " \
	"FIELD_IMPLEMENT foo; FIELD_IMPLEMENT bar; " \
	"FUNCTION_IMPLEMENT apple; FUNCTION_IMPLEMENT banana;"

#define TEST_RESULT_VAR_ARGS	\
	"FUNCTION_DECLARE apple; FUNCTION_DECLARE banana; FUNCTION_DECLARE pear; " \
	"FIELD_DECLARE foo; FIELD_DECLARE bar; " \
	"FIELD_IMPLEMENT foo; FIELD_IMPLEMENT bar; " \
	"FUNCTION_IMPLEMENT apple; FUNCTION_IMPLEMENT banana; FUNCTION_IMPLEMENT pear;"

#define TEST_RESULT_3_LISTS	\
	"FUNCTION_DECLARE apple; FUNCTION_DECLARE banana; FUNCTION_DECLARE pear; " \
	"INTERFACE_IMPLEMENT hello; INTERFACE_IMPLEMENT goodbye; " \
	"FIELD_DECLARE foo; FIELD_DECLARE bar; " \
	"FIELD_IMPLEMENT foo; FIELD_IMPLEMENT bar; " \
	"FUNCTION_IMPLEMENT apple; FUNCTION_IMPLEMENT banana; FUNCTION_IMPLEMENT pear;"

#define TEST_RESULT_EMPTY_LIST	\
	"FUNCTION_DECLARE apple; FUNCTION_DECLARE banana; FUNCTION_DECLARE pear; " \
	"INTERFACE_IMPLEMENT hello; INTERFACE_IMPLEMENT goodbye; " \
	"" \
	"" \
	"FUNCTION_IMPLEMENT apple; FUNCTION_IMPLEMENT banana; FUNCTION_IMPLEMENT pear;"

#define TEST_RESULT_LISTS_OF_LISTS	\
	"FUNCTION_DECLARE int add(int nValue); FUNCTION_DECLARE char * toString(void); FUNCTION_DECLARE void request(char * url, char * headers); " \
	"INTERFACE_IMPLEMENT hello; INTERFACE_IMPLEMENT goodbye; " \
	"" \
	"" \
	"FUNCTION_IMPLEMENT int add(int nValue){}; FUNCTION_IMPLEMENT char * toString(void){}; FUNCTION_IMPLEMENT void request(char * url, char * headers);"

#define FOREACH_REMAINDER_20(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARG14, ARG15, ARG16, ARG17, ARG18, ARG19, ARGS...) ARGS
#define FOREACH_REMAINDER_19(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARG14, ARG15, ARG16, ARG17, ARG18, ARGS...) ARGS
#define FOREACH_REMAINDER_18(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARG14, ARG15, ARG16, ARG17, ARGS...) ARGS
#define FOREACH_REMAINDER_17(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARG14, ARG15, ARG16, ARGS...) ARGS
#define FOREACH_REMAINDER_16(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARG14, ARG15, ARGS...) ARGS
#define FOREACH_REMAINDER_15(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARG14, ARGS...) ARGS
#define FOREACH_REMAINDER_14(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARGS...) ARGS
#define FOREACH_REMAINDER_13(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARGS...) ARGS
#define FOREACH_REMAINDER_12(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARGS...) ARGS
#define FOREACH_REMAINDER_11(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARGS...) ARGS
#define FOREACH_REMAINDER_10(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARGS...) ARGS
#define FOREACH_REMAINDER_9(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARGS...) ARGS
#define FOREACH_REMAINDER_8(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARGS...) ARGS
#define FOREACH_REMAINDER_7(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARGS...) ARGS
#define FOREACH_REMAINDER_6(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARGS...) ARGS
#define FOREACH_REMAINDER_5(ARG0, ARG1, ARG2, ARG3, ARG4, ARGS...) ARGS
#define FOREACH_REMAINDER_4(ARG0, ARG1, ARG2, ARG3, ARGS...) ARGS
#define FOREACH_REMAINDER_3(ARG0, ARG1, ARG2, ARGS...) ARGS
#define FOREACH_REMAINDER_2(ARG0, ARG1, ARGS...) ARGS
#define FOREACH_REMAINDER_1(ARG0, ARGS...) ARGS
#define FOREACH_REMAINDER_0(ARGS...) ARGS
#define _FOREACH_REMAINDER(COUNT, ARGS...) FOREACH_REMAINDER_##COUNT(ARGS)
#define FOREACH_REMAINDER(COUNT, ARGS...) _FOREACH_REMAINDER(COUNT, ARGS)

#define FOREACH_SHIFT_20(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARG14, ARG15, ARG16, ARG17, ARG18, ARG19, ARGS...) ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARG14, ARG15, ARG16, ARG17, ARG18, ARG19
#define FOREACH_SHIFT_19(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARG14, ARG15, ARG16, ARG17, ARG18, ARGS...) ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARG14, ARG15, ARG16, ARG17, ARG18
#define FOREACH_SHIFT_18(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARG14, ARG15, ARG16, ARG17, ARGS...) ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARG14, ARG15, ARG16, ARG17
#define FOREACH_SHIFT_17(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARG14, ARG15, ARG16, ARGS...) ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARG14, ARG15, ARG16
#define FOREACH_SHIFT_16(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARG14, ARG15, ARGS...) ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARG14, ARG15
#define FOREACH_SHIFT_15(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARG14, ARGS...) ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARG14
#define FOREACH_SHIFT_14(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13, ARGS...) ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARG13
#define FOREACH_SHIFT_13(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12, ARGS...) ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARG12
#define FOREACH_SHIFT_12(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11, ARGS...) ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARG11
#define FOREACH_SHIFT_11(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10, ARGS...) ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARG10
#define FOREACH_SHIFT_10(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9, ARGS...) ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9
#define FOREACH_SHIFT_9(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARGS...) ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8
#define FOREACH_SHIFT_8(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARGS...) ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7
#define FOREACH_SHIFT_7(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARGS...) ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6
#define FOREACH_SHIFT_6(ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARGS...) ARG0, ARG1, ARG2, ARG3, ARG4, ARG5
#define FOREACH_SHIFT_5(ARG0, ARG1, ARG2, ARG3, ARG4, ARGS...) ARG0, ARG1, ARG2, ARG3, ARG4
#define FOREACH_SHIFT_4(ARG0, ARG1, ARG2, ARG3, ARGS...) ARG0, ARG1, ARG2, ARG3
#define FOREACH_SHIFT_3(ARG0, ARG1, ARG2, ARGS...) ARG0, ARG1, ARG2
#define FOREACH_SHIFT_2(ARG0, ARG1, ARGS...) ARG0, ARG1
#define FOREACH_SHIFT_1(ARG0, ARGS...) ARG0
#define FOREACH_SHIFT_0(ARGS...)
#define _FOREACH_SHIFT(COUNT, ARGS...) FOREACH_SHIFT_##COUNT(ARGS)
#define FOREACH_SHIFT(COUNT, ARGS...) _FOREACH_SHIFT(COUNT, ARGS)

#define _FOREACHSHIFTPaste(ARG1,ARG2) ARG1##ARG2
#define FOREACHSHIFTPaste(ARG1,ARG2) _FOREACHSHIFTPaste(ARG1,ARG2)

#define FOREACHSHIFT4_0(MACRO,COUNT,ARGS...) MACRO(0,OOOIsEmpty(FOREACH_REMAINDER(ARGS)),4,COUNT,FOREACH_SHIFT(COUNT,ARGS),FOREACHSHIFTPaste(FOREACHSHIFT5_,OOOIsEmpty(FOREACH_REMAINDER(ARGS)))(MACRO,FOREACH_REMAINDER(ARGS)))
#define FOREACHSHIFT4_1(MACRO,ARGS...)
#define FOREACHSHIFT3_0(MACRO,COUNT,ARGS...) MACRO(0,OOOIsEmpty(FOREACH_REMAINDER(ARGS)),3,COUNT,FOREACH_SHIFT(COUNT,ARGS),FOREACHSHIFTPaste(FOREACHSHIFT4_,OOOIsEmpty(FOREACH_REMAINDER(ARGS)))(MACRO,FOREACH_REMAINDER(ARGS)))
#define FOREACHSHIFT3_1(MACRO,ARGS...)
#define FOREACHSHIFT2_0(MACRO,COUNT,ARGS...) MACRO(0,OOOIsEmpty(FOREACH_REMAINDER(ARGS)),2,COUNT,FOREACH_SHIFT(COUNT,ARGS),FOREACHSHIFTPaste(FOREACHSHIFT3_,OOOIsEmpty(FOREACH_REMAINDER(ARGS)))(MACRO,FOREACH_REMAINDER(ARGS)))
#define FOREACHSHIFT2_1(MACRO,ARGS...)
#define FOREACHSHIFT1_0(MACRO,COUNT,ARGS...) MACRO(0,OOOIsEmpty(FOREACH_REMAINDER(ARGS)),1,COUNT,FOREACH_SHIFT(COUNT,ARGS),FOREACHSHIFTPaste(FOREACHSHIFT2_,OOOIsEmpty(FOREACH_REMAINDER(ARGS)))(MACRO,FOREACH_REMAINDER(ARGS)))
#define FOREACHSHIFT1_1(MACRO,ARGS...)
#define FOREACHSHIFT0_0(MACRO,COUNT,ARGS...) MACRO(1,OOOIsEmpty(FOREACH_REMAINDER(ARGS)),0,COUNT,FOREACH_SHIFT(COUNT,ARGS),FOREACHSHIFTPaste(FOREACHSHIFT1_,OOOIsEmpty(FOREACH_REMAINDER(ARGS)))(MACRO,FOREACH_REMAINDER(ARGS)))
#define FOREACHSHIFT0_1(MACRO,ARGS...)
#define FOREACHSHIFT(MACRO,ARGS...) FOREACHSHIFTPaste(FOREACHSHIFT0_,OOOIsEmpty(ARGS))(MACRO,ARGS)

#define FUNCTION_DECLARE(FIRST, LAST, ITERATION, FUNCTION, REMAINDER...) \
	FUNCTION_DECLARE FUNCTION; REMAINDER
#define FUNCTIONS_DECLARE(ARGS...) \
	OOOForEach(FUNCTION_DECLARE, ARGS)

#define FUNCTION_IMPLEMENT(FIRST, LAST, ITERATION, FUNCTION, REMAINDER...) \
	FUNCTION_IMPLEMENT FUNCTION; REMAINDER
#define FUNCTIONS_IMPLEMENT(ARGS...) \
	OOOForEach(FUNCTION_IMPLEMENT, ARGS)

#define FIELD_DECLARE(FIRST, LAST, ITERATION, FIELD, REMAINDER...) \
	FIELD_DECLARE FIELD; REMAINDER
#define FIELDS_DECLARE(ARGS...) \
	OOOForEach(FIELD_DECLARE, ARGS)

#define FIELD_IMPLEMENT(FIRST, LAST, ITERATION, FIELD, REMAINDER...) \
	FIELD_IMPLEMENT FIELD; REMAINDER
#define FIELDS_IMPLEMENT(ARGS...) \
	OOOForEach(FIELD_IMPLEMENT, ARGS)

#define INTERFACE_IMPLEMENT(FIRST, LAST, ITERATION, INTERFACE, REMAINDER...) \
	INTERFACE_IMPLEMENT INTERFACE; REMAINDER
#define INTERFACES_IMPLEMENT(ARGS...) \
	OOOForEach(INTERFACE_IMPLEMENT, ARGS)

#define FUNCTION_IMPLEMENTATION0(RETURN, NAME, ARGS...) \
	RETURN NAME(ARGS){}
#define FUNCTION_IMPLEMENTATION1(RETURN, NAME, ARGS...) \
	RETURN NAME(void){}
#define FUNCTION_IMPLEMENTATION(RETURN, NAME, ARGS...) OOOSimplePaste(FUNCTION_IMPLEMENTATION,OOOIsEmpty(ARGS))(RETURN, NAME, ARGS)

#define FUNCTION2_IMPLEMENT(FIRST, LAST, ITERATION, ARGS...) \
	FUNCTION_IMPLEMENT FUNCTION_IMPLEMENTATION(FOREACH_SHIFT(ARGS)); FOREACH_REMAINDER(ARGS)
#define FUNCTIONS2_IMPLEMENT(ARGS...) \
	FOREACHSHIFT(FUNCTION2_IMPLEMENT, ARGS)

#define FUNCTION_PROTOTYPE0(RETURN, NAME, ARGS...) \
	RETURN NAME(ARGS)
#define FUNCTION_PROTOTYPE1(RETURN, NAME, ARGS...) \
	RETURN NAME(void)
#define FUNCTION_PROTOTYPE(RETURN, NAME, ARGS...) OOOSimplePaste(FUNCTION_PROTOTYPE,OOOIsEmpty(ARGS))(RETURN, NAME, ARGS)

#define FUNCTION2_DECLARE(FIRST, LAST, ITERATION, ARGS...) \
	FUNCTION_DECLARE FUNCTION_PROTOTYPE(FOREACH_SHIFT(ARGS)); FOREACH_REMAINDER(ARGS)
#define FUNCTIONS2_DECLARE(ARGS...) \
	FOREACHSHIFT(FUNCTION2_DECLARE, ARGS)

#define CLASS(ARGS...) \
	FUNCTIONS_DECLARE(OOOPre(ARGS)) \
	FIELDS_DECLARE(OOOPre(OOOPost(ARGS))) \
	FIELDS_IMPLEMENT(OOOPre(OOOPost(ARGS))) \
	FUNCTIONS_IMPLEMENT(OOOPre(ARGS))

#define CLASS2(ARGS...) \
	FUNCTIONS_DECLARE(OOOPre(ARGS)) \
	INTERFACES_IMPLEMENT(OOOPre(OOOPost(OOOPost(ARGS)))) \
	FIELDS_DECLARE(OOOPre(OOOPost(ARGS))) \
	FIELDS_IMPLEMENT(OOOPre(OOOPost(ARGS))) \
	FUNCTIONS_IMPLEMENT(OOOPre(ARGS))

#define CLASS3(ARGS...) \
	FUNCTIONS2_DECLARE(OOOPre(ARGS)) \
	INTERFACES_IMPLEMENT(OOOPre(OOOPost(OOOPost(ARGS)))) \
	FIELDS_DECLARE(OOOPre(OOOPost(ARGS))) \
	FIELDS_IMPLEMENT(OOOPre(OOOPost(ARGS))) \
	FUNCTIONS2_IMPLEMENT(OOOPre(ARGS))

#define _VARLISTPaste(ARG1,ARG2) ARG1##ARG2
#define VARLISTPaste(ARG1,ARG2) _VARLISTPaste(ARG1,ARG2)

#define VARLIST0(ARGS...) OOOCount(ARGS), ARGS
#define VARLIST1(ARGS...) 0
#define VARLIST(ARGS...) VARLISTPaste(VARLIST, OOOIsEmpty(ARGS))(ARGS)
#define FUNCTIONS(ARGS...) VARLIST(ARGS)
#define FIELDS(ARGS...) VARLIST(ARGS)
#define INTERFACES(ARGS...) VARLIST(ARGS)
#define FUNCTION(ARGS...) VARLIST(ARGS)

OOOTest(OOOMultiVarArg)
{
	char * szTest;

	// should handle 2 functions and 2 fields
	szTest = OOOQuote(CLASS(FUNCTIONS(apple, banana), FIELDS(foo, bar)));
	if (O_strcmp(TEST_RESULT_2_ARGS, szTest) != 0)
	{
		OOOError("expected: %s\nReceived: %s", TEST_RESULT_2_ARGS, szTest);
	}

	// should handle 3 functions and 2 fields
	szTest = OOOQuote(CLASS(FUNCTIONS(apple, banana, pear), FIELDS(foo, bar)));
	if (O_strcmp(TEST_RESULT_VAR_ARGS, szTest) != 0)
	{
		OOOError("expected: %s\nReceived: %s", TEST_RESULT_VAR_ARGS, szTest);
	}

	// should handle 3 lists
	szTest = OOOQuote(CLASS2(FUNCTIONS(apple, banana, pear), FIELDS(foo, bar), INTERFACES(hello, goodbye)));
	if (O_strcmp(TEST_RESULT_3_LISTS, szTest) != 0)
	{
		OOOError("expected: %s\nReceived: %s", TEST_RESULT_3_LISTS, szTest);
	}

	// should handle an empty list
	szTest = OOOQuote(CLASS2(FUNCTIONS(apple, banana, pear), FIELDS(), INTERFACES(hello, goodbye)));
	if (O_strcmp(TEST_RESULT_EMPTY_LIST, szTest) != 0)
	{
		OOOError("expected: %s\nReceived: %s", TEST_RESULT_EMPTY_LIST, szTest);
	}

	// should handle lists of lists
//	szTest = OOOQuote(CLASS3(FUNCTIONS(FUNCTION(int, add, int nValue), FUNCTION(char *, toString), FUNCTION(void, request, char * url, char * headers)), FIELDS(), INTERFACES(hello, goodbye)));
//	if (O_strcmp(TEST_RESULT_EMPTY_LIST, szTest) != 0)
//	{
//		OOOError("expected: %s\nReceived: %s", TEST_RESULT_EMPTY_LIST, szTest);
//	}
}
